
services:

  app:
    build: .
    container_name: user-profile-api

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy
      mock-service:
        condition: service_healthy

    volumes:
      - .:/app

  db:
    image: postgres:16

    container_name: postgres-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_profiles_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mock-service:
    build:
      context: ./mock-service
      dockerfile: Dockerfile

    container_name: mock-service

    ports:
      - "8081:8081"

    environment:
      MOCK_SERVICE_FAILURE_RATE: ${MOCK_SERVICE_FAILURE_RATE}
      MOCK_SERVICE_DELAY_MS: ${MOCK_SERVICE_DELAY_MS}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: